# Generated by Django 3.1.6 on 2021-08-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersMail',
            fields=[
                ('email_id', models.EmailField(max_length=20, primary_key=True, serialize=False)),
                ('email_sent_time', models.DateTimeField(auto_now_add=True)),
                ('email_status', models.CharField(max_length=10)),
            ],
        ),
    ]
